### ISSUE TITLE
Set up REST API ednpoints

### ISSUE THREAD

**Issue by JasonHoffmann** [JasonHoffmann/wp-styleguide#1]
One question is, should this plugin use a custom post type, or should we set up a custom endpoint system using just the base API. I think we can just store all data in a custom post type, but we will need an options endpoint as well, so it may make sense to set up a [custom namespace](http://v2.wp-api.org/extending/adding/) for everything. If we go with a post type, we'll need to require the latest version of the REST API plugin, otherwise we can build off of what's already in core. Thoughts?

**Comment by SolomonSScott** [comment]
I would suggest we use set a custom post type. It allow us to store what we need and keep it separate from everything else in the users wp install. Since we'll already require to the REST API for the options, it should be fine.

**Comment by JasonHoffmann** [comment]
Ok cool, do you think we should add just a basic endpoint in the default 'wp/v2/' namespace like here: http://v2.wp-api.org/extending/custom-content-types/ or go about creating our own namespace like here: http://v2.wp-api.org/extending/adding/. The latter is easier, but the former gives us more flexibility. I'm a bit on the fence.

**Comment by SolomonSScott** [comment]
I think we should add our own namespace. I'm leaning towards a bit more flexibility.

**Comment by JasonHoffmann** [comment]
Cool, I can grab this as my first thing to do. I'll set up a basic custom post type and controller for the API.
